import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcGx5dHFncXZ6ZWxjY2JtenNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNjMxNDYsImV4cCI6MjA4ODYzOTE0Nn0.nQJNiVXiQbpzjGnWaf9LfxZXiIpf1QAynhUff-GNjuM
const supabaseAnonKey = process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcGx5dHFncXZ6ZWxjY2JtenNmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzA2MzE0NiwiZXhwIjoyMDg4NjM5MTQ2fQ.o_zSo6o12xyh7IqMOpBhdpJfgKfAh5FdHQGteZ_4w_s

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
